import type { ViewBounds } from '../types';

export interface FormulaMetadata {
  id: string;
  family: 'classic' | 'burning-ship' | 'newton' | 'magnet' | 'phoenix' | 'transcendental' | 'exotic';
  defaultBounds: ViewBounds;
  suggestedPalette: number;
  thumbnailParams?: Record<string, number>;
  difficulty: 'easy' | 'medium' | 'hard';
  description?: string;
}

export const FORMULA_CATALOG: FormulaMetadata[] = [
  // === Original 4 formulas (from Phase 1.1) ===
  {
    id: 'mandelbrot',
    family: 'classic',
    defaultBounds: { centerX: -0.5, centerY: 0, zoom: 0.4 },
    suggestedPalette: 0,
    difficulty: 'easy',
    description: 'The classic Mandelbrot set',
  },
  {
    id: 'burningShip',
    family: 'burning-ship',
    defaultBounds: { centerX: -0.5, centerY: -0.5, zoom: 0.4 },
    suggestedPalette: 0,
    difficulty: 'easy',
    description: 'Burning Ship fractal',
  },
  {
    id: 'tricorn',
    family: 'classic',
    defaultBounds: { centerX: -0.12, centerY: 0, zoom: 0.65 },
    suggestedPalette: 0,
    difficulty: 'easy',
    description: 'Tricorn (conjugate Mandelbrot)',
  },
  {
    id: 'phoenix',
    family: 'phoenix',
    defaultBounds: { centerX: -0.35, centerY: 0, zoom: 0.55 },
    suggestedPalette: 2,
    difficulty: 'medium',
    description: 'Phoenix fractal with memory',
  },

  // === Classic Family (new in Phase 1.2) ===
  {
    id: 'lambda',
    family: 'classic',
    defaultBounds: { centerX: 0.5, centerY: 0, zoom: 0.15 },
    suggestedPalette: 0,
    difficulty: 'easy',
    description: 'Lambda fractal',
  },
  {
    id: 'quadJulia',
    family: 'classic',
    defaultBounds: { centerX: 0, centerY: 0, zoom: 0.85 },
    suggestedPalette: 1,
    difficulty: 'easy',
    description: 'Quartic Julia set',
  },
  {
    id: 'cubicMandelbrot',
    family: 'classic',
    defaultBounds: { centerX: -0.15, centerY: 0, zoom: 0.55 },
    suggestedPalette: 1,
    difficulty: 'easy',
    description: 'Cubic Mandelbrot (z^3 + c)',
  },
  {
    id: 'quarticMandelbrot',
    family: 'classic',
    defaultBounds: { centerX: -0.1, centerY: 0, zoom: 0.6 },
    suggestedPalette: 1,
    difficulty: 'easy',
    description: 'Quartic Mandelbrot (z^4 + c)',
  },
  {
    id: 'mandelbox',
    family: 'classic',
    defaultBounds: { centerX: 0.0, centerY: 0, zoom: 0.65 },
    suggestedPalette: 3,
    difficulty: 'medium',
    description: 'Mandelbox 3D-like folding',
    thumbnailParams: { u_mandelboxScale: 2.0 },
  },
  {
    id: 'multicorn4',
    family: 'classic',
    defaultBounds: { centerX: -0.1, centerY: 0.0, zoom: 0.72 },
    suggestedPalette: 1,
    difficulty: 'easy',
    description: 'Fourth-order multicorn using the conjugate quartic map',
  },
  {
    id: 'multicorn5',
    family: 'classic',
    defaultBounds: { centerX: -0.08, centerY: 0.0, zoom: 0.78 },
    suggestedPalette: 1,
    difficulty: 'easy',
    description: 'Fifth-order multicorn using the conjugate quintic map',
  },
  {
    id: 'chebyshev2',
    family: 'classic',
    defaultBounds: { centerX: 0.0, centerY: 0.0, zoom: 0.78 },
    suggestedPalette: 1,
    difficulty: 'easy',
    description: 'Chebyshev T2 polynomial map (2*z^2 - 1 + c)',
  },
  {
    id: 'chebyshev3',
    family: 'classic',
    defaultBounds: { centerX: -0.05, centerY: 0.0, zoom: 0.55 },
    suggestedPalette: 1,
    difficulty: 'easy',
    description: 'Chebyshev T3 polynomial map (4*z^3 - 3*z + c)',
  },
  {
    id: 'chebyshev4',
    family: 'classic',
    defaultBounds: { centerX: -0.02, centerY: 0.0, zoom: 0.7 },
    suggestedPalette: 1,
    difficulty: 'easy',
    description: 'Chebyshev T4 polynomial map (8*z^4 - 8*z^2 + 1 + c)',
  },
  {
    id: 'chebyshev5',
    family: 'classic',
    defaultBounds: { centerX: 0.0, centerY: 0.0, zoom: 0.72 },
    suggestedPalette: 1,
    difficulty: 'medium',
    description: 'Chebyshev T5 polynomial map (16*z^5 - 20*z^3 + 5*z + c)',
  },
  {
    id: 'multicorn6',
    family: 'classic',
    defaultBounds: { centerX: -0.04, centerY: 0.0, zoom: 0.86 },
    suggestedPalette: 1,
    difficulty: 'medium',
    description: 'Sixth-order multicorn using the conjugate sextic map',
  },
  {
    id: 'multicorn7',
    family: 'classic',
    defaultBounds: { centerX: -0.02, centerY: 0.0, zoom: 0.9 },
    suggestedPalette: 1,
    difficulty: 'medium',
    description: 'Seventh-order multicorn using the conjugate septic map',
  },
  {
    id: 'perpendicularMandelbrot',
    family: 'classic',
    defaultBounds: { centerX: -0.4, centerY: 0.0, zoom: 0.42 },
    suggestedPalette: 0,
    difficulty: 'medium',
    description: 'Perpendicular Mandelbrot with swapped absolute-value folding',
  },
  {
    id: 'perpendicularTricorn',
    family: 'classic',
    defaultBounds: { centerX: -0.45, centerY: 0.0, zoom: 0.28 },
    suggestedPalette: 0,
    difficulty: 'medium',
    description: 'Perpendicular Tricorn with folded real axis before conjugation',
  },
  {
    id: 'perpendicularCeltic',
    family: 'classic',
    defaultBounds: { centerX: -0.46, centerY: 0.0, zoom: 0.26 },
    suggestedPalette: 0,
    difficulty: 'medium',
    description: 'Perpendicular Celtic Mandelbrot using folded real-axis symmetry',
  },
  {
    id: 'cubicPerpendicularMandelbrot',
    family: 'classic',
    defaultBounds: { centerX: -0.34, centerY: 0.0, zoom: 0.3 },
    suggestedPalette: 1,
    difficulty: 'medium',
    description: 'Cubic perpendicular Mandelbrot with absolute-value folding',
  },
  {
    id: 'quarticPerpendicularMandelbrot',
    family: 'classic',
    defaultBounds: { centerX: -0.32, centerY: 0.0, zoom: 0.28 },
    suggestedPalette: 1,
    difficulty: 'medium',
    description: 'Quartic perpendicular Mandelbrot with absolute-value folding',
  },
  {
    id: 'rabbitJulia',
    family: 'classic',
    defaultBounds: { centerX: 0.0, centerY: 0.0, zoom: 0.95 },
    suggestedPalette: 4,
    difficulty: 'easy',
    description: 'Fixed-parameter Douady rabbit Julia portrait',
  },

  // === Newton Family ===
  {
    id: 'newton3',
    family: 'newton',
    defaultBounds: { centerX: -0.18, centerY: 0.1, zoom: 1.35 },
    suggestedPalette: 2,
    difficulty: 'medium',
    description: 'Newton method for z^3 - 1',
  },
  {
    id: 'newton4',
    family: 'newton',
    defaultBounds: { centerX: 0.08, centerY: 0.08, zoom: 1.45 },
    suggestedPalette: 2,
    difficulty: 'medium',
    description: 'Newton method for z^4 - 1',
  },
  {
    id: 'newtonSin',
    family: 'newton',
    defaultBounds: { centerX: 0.3, centerY: 0, zoom: 2.6 },
    suggestedPalette: 2,
    difficulty: 'hard',
    description: 'Newton method for sin(z)',
  },
  {
    id: 'newtonCos',
    family: 'newton',
    defaultBounds: { centerX: 0.0, centerY: 0.0, zoom: 2.1 },
    suggestedPalette: 2,
    difficulty: 'medium',
    description: 'Newton method for cos(z) - z',
  },
  {
    id: 'newton5',
    family: 'newton',
    defaultBounds: { centerX: 0.0, centerY: 0.0, zoom: 1.6 },
    suggestedPalette: 2,
    difficulty: 'medium',
    description: 'Newton method for z^5 - 1',
  },
  {
    id: 'newton6',
    family: 'newton',
    defaultBounds: { centerX: 0.0, centerY: 0.0, zoom: 1.75 },
    suggestedPalette: 2,
    difficulty: 'hard',
    description: 'Newton method for z^6 - 1',
  },
  {
    id: 'newtonSinh',
    family: 'newton',
    defaultBounds: { centerX: 0.0, centerY: 0.0, zoom: 1.8 },
    suggestedPalette: 2,
    difficulty: 'hard',
    description: 'Newton method for sinh(z)',
  },
  {
    id: 'newtonCosh',
    family: 'newton',
    defaultBounds: { centerX: 0.0, centerY: 0.0, zoom: 1.6 },
    suggestedPalette: 2,
    difficulty: 'hard',
    description: 'Newton method for cosh(z) - 1',
  },
  {
    id: 'halleyCubic',
    family: 'newton',
    defaultBounds: { centerX: 0.0, centerY: 0.0, zoom: 1.75 },
    suggestedPalette: 2,
    difficulty: 'hard',
    description: 'Halley iteration for cubic roots',
  },
  {
    id: 'novaClassic',
    family: 'newton',
    defaultBounds: { centerX: 0.0, centerY: 0.0, zoom: 1.6 },
    suggestedPalette: 3,
    difficulty: 'hard',
    description: 'Classic Nova basin around the cubic root system',
  },
  {
    id: 'novaSine',
    family: 'newton',
    defaultBounds: { centerX: 0.0, centerY: 0.0, zoom: 1.4 },
    suggestedPalette: 3,
    difficulty: 'hard',
    description: 'Nova-style sine basin with Julia-style parameter kick',
  },
  {
    id: 'novaCos',
    family: 'newton',
    defaultBounds: { centerX: 0.0, centerY: 0.0, zoom: 2.05 },
    suggestedPalette: 3,
    difficulty: 'hard',
    description: 'Nova-style cosine basin around cos(z) - z roots',
  },

  // === Magnet Family ===
  {
    id: 'magnet1',
    family: 'magnet',
    defaultBounds: { centerX: 0, centerY: 0, zoom: 0.6 },
    suggestedPalette: 3,
    difficulty: 'medium',
    description: 'Magnet type 1',
  },
  {
    id: 'magnet2',
    family: 'magnet',
    defaultBounds: { centerX: 0.15, centerY: 0, zoom: 0.6 },
    suggestedPalette: 3,
    difficulty: 'hard',
    description: 'Magnet type 2',
  },

  // === Phoenix Family ===
  {
    id: 'phoenixMulti',
    family: 'phoenix',
    defaultBounds: { centerX: -0.25, centerY: 0, zoom: 0.55 },
    suggestedPalette: 2,
    difficulty: 'medium',
    description: 'Phoenix variant with tunable feedback term',
    thumbnailParams: { u_phoenixMultiP: 0.5 },
  },

  // === Exotic Family ===
  {
    id: 'collatz',
    family: 'exotic',
    defaultBounds: { centerX: 0.25, centerY: 0.1, zoom: 2.4 },
    suggestedPalette: 4,
    difficulty: 'hard',
    description: 'Complex Collatz-inspired iterative map',
  },
  {
    id: 'spider',
    family: 'exotic',
    defaultBounds: { centerX: -0.35, centerY: 0.08, zoom: 0.52 },
    suggestedPalette: 0,
    difficulty: 'medium',
    description: 'Hybrid quadratic map with c/z feedback',
  },
  {
    id: 'buffalo',
    family: 'exotic',
    defaultBounds: { centerX: -0.5, centerY: -0.3, zoom: 0.4 },
    suggestedPalette: 0,
    difficulty: 'easy',
    description: 'Buffalo fractal',
  },
  {
    id: 'zubieta',
    family: 'exotic',
    defaultBounds: { centerX: -0.5, centerY: 0, zoom: 0.4 },
    suggestedPalette: 0,
    difficulty: 'easy',
    description: 'Absolute-value quadratic variant',
  },
  {
    id: 'rationalMap1',
    family: 'exotic',
    defaultBounds: { centerX: -0.08, centerY: 0.0, zoom: 0.68 },
    suggestedPalette: 4,
    difficulty: 'hard',
    description: 'Rational map z^2 / (z + c)',
  },
  {
    id: 'rationalMap2',
    family: 'exotic',
    defaultBounds: { centerX: -0.06, centerY: 0.0, zoom: 0.66 },
    suggestedPalette: 4,
    difficulty: 'hard',
    description: 'Rational map z^3 / (z^2 + c)',
  },
  {
    id: 'mcMullen23',
    family: 'exotic',
    defaultBounds: { centerX: 0.0, centerY: 0.0, zoom: 0.82 },
    suggestedPalette: 3,
    difficulty: 'hard',
    description: 'McMullen map z^2 + c / z^3',
  },
  {
    id: 'mcMullen32',
    family: 'exotic',
    defaultBounds: { centerX: 0.0, centerY: 0.0, zoom: 0.84 },
    suggestedPalette: 3,
    difficulty: 'hard',
    description: 'McMullen map z^3 + c / z^2',
  },
  {
    id: 'mcMullen34',
    family: 'exotic',
    defaultBounds: { centerX: 0.0, centerY: 0.0, zoom: 0.88 },
    suggestedPalette: 3,
    difficulty: 'hard',
    description: 'McMullen map z^3 + c / z^4',
  },
  {
    id: 'reciprocalQuadratic',
    family: 'exotic',
    defaultBounds: { centerX: 0.0, centerY: 0.0, zoom: 0.92 },
    suggestedPalette: 4,
    difficulty: 'hard',
    description: 'Reciprocal quadratic map 1 / (z^2 + c)',
  },
  {
    id: 'reciprocalCubic',
    family: 'exotic',
    defaultBounds: { centerX: 0.0, centerY: 0.0, zoom: 0.95 },
    suggestedPalette: 4,
    difficulty: 'hard',
    description: 'Reciprocal cubic map 1 / (z^3 + c)',
  },
  {
    id: 'invertedLambda',
    family: 'exotic',
    defaultBounds: { centerX: 0.18, centerY: 0.0, zoom: 0.5 },
    suggestedPalette: 0,
    difficulty: 'medium',
    description: 'Inverted Lambda-style rational hybrid',
  },
  {
    id: 'novaBasin',
    family: 'exotic',
    defaultBounds: { centerX: 0.0, centerY: 0.0, zoom: 1.45 },
    suggestedPalette: 3,
    difficulty: 'hard',
    description: 'Nova-style basin variant with twisted correction',
  },
  {
    id: 'zaslavskyMap',
    family: 'exotic',
    defaultBounds: { centerX: 0.0, centerY: 0.0, zoom: 1.15 },
    suggestedPalette: 4,
    difficulty: 'hard',
    description: 'Zaslavsky-inspired complex swirl map',
  },
  {
    id: 'expJulia',
    family: 'transcendental',
    defaultBounds: { centerX: -0.2, centerY: 0.15, zoom: 2.2 },
    suggestedPalette: 2,
    difficulty: 'medium',
    description: 'Exponential Julia set',
  },
  {
    id: 'cosMandelb',
    family: 'transcendental',
    defaultBounds: { centerX: -1.2, centerY: 0.0, zoom: 0.25 },
    suggestedPalette: 2,
    difficulty: 'medium',
    description: 'Cosine Mandelbrot map cos(z) + c',
  },
  {
    id: 'expMandelbrot',
    family: 'transcendental',
    defaultBounds: { centerX: -0.3, centerY: 0.0, zoom: 1.6 },
    suggestedPalette: 2,
    difficulty: 'medium',
    description: 'Exponential escape-time map exp(z) + c',
  },
  {
    id: 'atanhMandelbrot',
    family: 'transcendental',
    defaultBounds: { centerX: -0.12, centerY: 0.0, zoom: 1.22 },
    suggestedPalette: 2,
    difficulty: 'medium',
    description: 'Inverse hyperbolic tangent Mandelbrot map',
  },
  {
    id: 'atanhJulia',
    family: 'transcendental',
    defaultBounds: { centerX: 0.04, centerY: 0.0, zoom: 1.04 },
    suggestedPalette: 4,
    difficulty: 'medium',
    description: 'Inverse hyperbolic tangent Julia map',
  },
  {
    id: 'asinhMandelbrot',
    family: 'transcendental',
    defaultBounds: { centerX: 0.0, centerY: 0.0, zoom: 1.0 },
    suggestedPalette: 2,
    difficulty: 'medium',
    description: 'Inverse hyperbolic sine Mandelbrot map',
  },
  {
    id: 'asinhJulia',
    family: 'transcendental',
    defaultBounds: { centerX: 0.0, centerY: 0.02, zoom: 0.98 },
    suggestedPalette: 4,
    difficulty: 'medium',
    description: 'Inverse hyperbolic sine Julia map',
  },
  {
    id: 'acoshMandelbrot',
    family: 'transcendental',
    defaultBounds: { centerX: 0.18, centerY: 0.0, zoom: 1.08 },
    suggestedPalette: 2,
    difficulty: 'hard',
    description: 'Inverse hyperbolic cosine Mandelbrot map',
  },
  {
    id: 'acoshJulia',
    family: 'transcendental',
    defaultBounds: { centerX: 0.18, centerY: 0.02, zoom: 1.02 },
    suggestedPalette: 4,
    difficulty: 'hard',
    description: 'Inverse hyperbolic cosine Julia map',
  },
  {
    id: 'cothMandelbrot',
    family: 'transcendental',
    defaultBounds: { centerX: 0.0, centerY: 0.0, zoom: 0.75 },
    suggestedPalette: 2,
    difficulty: 'hard',
    description: 'Hyperbolic cotangent Mandelbrot map',
  },
  {
    id: 'cothJulia',
    family: 'transcendental',
    defaultBounds: { centerX: 0.0, centerY: 0.0, zoom: 0.78 },
    suggestedPalette: 4,
    difficulty: 'hard',
    description: 'Hyperbolic cotangent Julia map',
  },
  {
    id: 'logJulia',
    family: 'transcendental',
    defaultBounds: { centerX: 0.1, centerY: 0.0, zoom: 0.9 },
    suggestedPalette: 4,
    difficulty: 'hard',
    description: 'Logarithmic Julia map',
  },

  // === Transcendental (6) ===
  {
    id: 'sineMandelb',
    family: 'transcendental',
    defaultBounds: { centerX: -0.25, centerY: 0.12, zoom: 1.25 },
    suggestedPalette: 2,
    difficulty: 'medium',
    description: 'Sine Mandelbrot',
  },
  {
    id: 'sineJulia',
    family: 'transcendental',
    defaultBounds: { centerX: 0.1, centerY: 0.12, zoom: 1.25 },
    suggestedPalette: 4,
    difficulty: 'medium',
    description: 'Sine Julia map sin(z) scaled by c',
  },
  {
    id: 'coshMandelb',
    family: 'transcendental',
    defaultBounds: { centerX: 0.18, centerY: 0, zoom: 1.2 },
    suggestedPalette: 2,
    difficulty: 'medium',
    description: 'Cosh Mandelbrot',
  },
  {
    id: 'sinhMandelb',
    family: 'transcendental',
    defaultBounds: { centerX: -0.16, centerY: 0.0, zoom: 1.15 },
    suggestedPalette: 2,
    difficulty: 'medium',
    description: 'Sinh Mandelbrot map sinh(z) + c',
  },
  {
    id: 'coshJulia',
    family: 'transcendental',
    defaultBounds: { centerX: 0.08, centerY: 0.14, zoom: 1.22 },
    suggestedPalette: 4,
    difficulty: 'medium',
    description: 'Cosh Julia map cosh(z) scaled by c',
  },
  {
    id: 'coshSinh',
    family: 'transcendental',
    defaultBounds: { centerX: 0.0, centerY: 0.0, zoom: 1.05 },
    suggestedPalette: 2,
    difficulty: 'medium',
    description: 'Hybrid hyperbolic map cosh(z) * sinh(z) + c',
  },
  {
    id: 'cosJulia',
    family: 'transcendental',
    defaultBounds: { centerX: 0.12, centerY: 0.18, zoom: 1.3 },
    suggestedPalette: 4,
    difficulty: 'medium',
    description: 'Cosine Julia',
  },
  {
    id: 'tanJulia',
    family: 'transcendental',
    defaultBounds: { centerX: 0.22, centerY: 0, zoom: 1.35 },
    suggestedPalette: 4,
    difficulty: 'medium',
    description: 'Tangent Julia',
  },
  {
    id: 'sinhJulia',
    family: 'transcendental',
    defaultBounds: { centerX: -0.18, centerY: 0.08, zoom: 1.25 },
    suggestedPalette: 4,
    difficulty: 'medium',
    description: 'Sinh Julia',
  },
  // === Classic Variants (5) ===
  {
    id: 'heart',
    family: 'classic',
    defaultBounds: { centerX: -0.5, centerY: 0, zoom: 0.4 },
    suggestedPalette: 0,
    difficulty: 'easy',
    description: 'Quadratic map folded on the real axis',
  },
  {
    id: 'manowar',
    family: 'classic',
    defaultBounds: { centerX: -0.5, centerY: 0, zoom: 0.4 },
    suggestedPalette: 0,
    difficulty: 'easy',
    description: 'Quadratic map with previous-orbit feedback',
  },
  {
    id: 'biomorph',
    family: 'classic',
    defaultBounds: { centerX: -0.1, centerY: 0, zoom: 0.6 },
    suggestedPalette: 1,
    difficulty: 'easy',
    description: 'Cubic biomorph-style polynomial map',
  },
  {
    id: 'cactus',
    family: 'classic',
    defaultBounds: { centerX: 0, centerY: 0, zoom: 0.4 },
    suggestedPalette: 1,
    difficulty: 'medium',
    description: 'Cubic cactus polynomial variant',
  },
  {
    id: 'logistic',
    family: 'classic',
    defaultBounds: { centerX: 0.0, centerY: 0, zoom: 0.4 },
    suggestedPalette: 0,
    difficulty: 'medium',
    description: 'Complex logistic map seeded near z = 0.5',
  },

  // === Burning Ship Variants (2) ===
  {
    id: 'celticMandelbar',
    family: 'burning-ship',
    defaultBounds: { centerX: -0.22, centerY: 0, zoom: 0.75 },
    suggestedPalette: 0,
    difficulty: 'easy',
    description: 'Conjugate Celtic variant in the Burning Ship family',
  },
  {
    id: 'burningShipImag',
    family: 'burning-ship',
    defaultBounds: { centerX: -0.5, centerY: -0.5, zoom: 0.4 },
    suggestedPalette: 0,
    difficulty: 'easy',
    description: 'Burning Ship variant folded on the imaginary axis',
  },
  {
    id: 'airship',
    family: 'burning-ship',
    defaultBounds: { centerX: -0.6, centerY: -0.35, zoom: 0.35 },
    suggestedPalette: 0,
    difficulty: 'medium',
    description: 'Airship variant with a stretched Burning Ship-style fold',
  },
  {
    id: 'celticMandelbrot',
    family: 'burning-ship',
    defaultBounds: { centerX: -0.42, centerY: 0.0, zoom: 0.48 },
    suggestedPalette: 0,
    difficulty: 'easy',
    description: 'Celtic-style Mandelbrot with real-axis folding',
  },
  {
    id: 'celticBurningShip',
    family: 'burning-ship',
    defaultBounds: { centerX: -0.42, centerY: -0.18, zoom: 0.48 },
    suggestedPalette: 0,
    difficulty: 'medium',
    description: 'Celtic Burning Ship with absolute-value real-axis carving',
  },
  {
    id: 'perpendicularBurningShip',
    family: 'burning-ship',
    defaultBounds: { centerX: -0.42, centerY: -0.12, zoom: 0.5 },
    suggestedPalette: 0,
    difficulty: 'medium',
    description: 'Perpendicular Burning Ship with swapped absolute folding',
  },
  {
    id: 'perpendicularCelticBurningShip',
    family: 'burning-ship',
    defaultBounds: { centerX: -0.42, centerY: -0.16, zoom: 0.46 },
    suggestedPalette: 0,
    difficulty: 'hard',
    description: 'Perpendicular Celtic Burning Ship with mirrored and celtic folding',
  },
  {
    id: 'burningShipCubic',
    family: 'burning-ship',
    defaultBounds: { centerX: -0.34, centerY: -0.08, zoom: 0.58 },
    suggestedPalette: 0,
    difficulty: 'medium',
    description: 'Cubic Burning Ship-style folded polynomial',
  },
  {
    id: 'burningShipQuartic',
    family: 'burning-ship',
    defaultBounds: { centerX: -0.32, centerY: -0.06, zoom: 0.62 },
    suggestedPalette: 0,
    difficulty: 'hard',
    description: 'Quartic Burning Ship-style folded polynomial',
  },
  {
    id: 'airshipCubic',
    family: 'burning-ship',
    defaultBounds: { centerX: -0.42, centerY: -0.16, zoom: 0.24 },
    suggestedPalette: 0,
    difficulty: 'hard',
    description: 'Cubic Airship variant with stronger folded keel structures',
  },

  // === Newton/Convergence (1) ===
  {
    id: 'newtonExp',
    family: 'newton',
    defaultBounds: { centerX: 0.0, centerY: 0, zoom: 2.0 },
    suggestedPalette: 2,
    difficulty: 'hard',
    description: 'Newton method for exp(z)',
  },

  // === Hybrid/Special (4) ===
  {
    id: 'tetration',
    family: 'exotic',
    defaultBounds: { centerX: 0.18, centerY: 0, zoom: 1.15 },
    suggestedPalette: 3,
    difficulty: 'hard',
    description: 'Iterated exponentiation map c^z',
  },
  {
    id: 'circleInversion',
    family: 'exotic',
    defaultBounds: { centerX: 0.0, centerY: 0.0, zoom: 0.95 },
    suggestedPalette: 4,
    difficulty: 'medium',
    description: 'Circle inversion map built from the reciprocal quadratic term',
  },
  {
    id: 'frothyBasin',
    family: 'exotic',
    defaultBounds: { centerX: 0.0, centerY: 0.0, zoom: 0.55 },
    suggestedPalette: 3,
    difficulty: 'medium',
    description: 'Quadratic basin with conjugate-coupled feedback',
  },
  {
    id: 'simonBrot',
    family: 'classic',
    defaultBounds: { centerX: -0.1, centerY: 0, zoom: 0.58 },
    suggestedPalette: 1,
    difficulty: 'easy',
    description: 'SimonBrot (z^4 + z^3 + c)',
  },
  {
    id: 'rings',
    family: 'exotic',
    defaultBounds: { centerX: -0.5, centerY: 0, zoom: 0.5 },
    suggestedPalette: 0,
    difficulty: 'medium',
    description: 'Quadratic map with reciprocal rings term',
    thumbnailParams: { u_ringsP: 0.5 },
  },
];

export function getFormulaMetadata(id: string): FormulaMetadata | undefined {
  return FORMULA_CATALOG.find((f) => f.id === id);
}

export function getDefaultBounds(id: string): ViewBounds {
  const meta = getFormulaMetadata(id);
  return meta?.defaultBounds ?? { centerX: -0.5, centerY: 0, zoom: 0.4 };
}
