import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';

const LOCALES = ['en', 'zh', 'pt', 'ko', 'ru', 'es', 'fr'] as const;
const OUTPUT_PATH = 'src/content/teaching/generated-content-registry.ts';

interface SelectionAsset {
  readonly schema: string;
  readonly packageCount: number;
  readonly contentUnitCount: number;
  readonly locales: readonly string[];
  readonly rows: ReadonlyArray<
    Readonly<{
      ordinal: number;
      batch: number;
      formulaId: string;
      sourceRevision: string;
      semanticHash: string;
    }>
  >;
}

function buildRegistrySource(repositoryRoot: string): string {
  const selectionBytes = readFileSync(
    join(repositoryRoot, 'resources/formula-library/v1/teaching-selection.v1.json'),
  );
  const authorityFiles = {
    anchors: join(
      repositoryRoot,
      'resources/formula-library/v1/teaching-semantic-anchors.v1.json',
    ),
    runtimeIndex: join(
      repositoryRoot,
      'public/formula-library/v1/runtime/published/index.json',
    ),
    ledger: join(
      repositoryRoot,
      'resources/formula-library/v1/teaching-review-ledger.v1.json',
    ),
    approval: join(
      repositoryRoot,
      'resources/formula-library/v1/teaching-review-evidence/maintainer-approval.v1.json',
    ),
    approvalPacket: join(
      repositoryRoot,
      'resources/formula-library/v1/teaching-review-evidence/maintainer-approval-packet.v1.json',
    ),
  } as const;
  const authorityBytes = Object.fromEntries(
    Object.entries(authorityFiles).map(([key, path]) => [key, readFileSync(path)]),
  ) as Record<keyof typeof authorityFiles, Buffer>;
  const selection = JSON.parse(selectionBytes.toString('utf8')) as SelectionAsset;
  const rows = [...selection.rows].sort((left, right) => left.ordinal - right.ordinal);
  if (
    selection.schema !== 'fractalpark-teaching-selection/v1' ||
    selection.packageCount !== 50 ||
    selection.contentUnitCount !== 350 ||
    JSON.stringify(selection.locales) !== JSON.stringify(LOCALES) ||
    rows.length !== 50 ||
    new Set(rows.map((row) => row.formulaId)).size !== 50 ||
    rows.some(
      (row, index) =>
        row.ordinal !== index + 1 ||
        row.batch !== Math.floor(index / 10) + 1 ||
        !/^[a-f0-9-]{36}$/.test(row.formulaId) ||
        !/^[a-f0-9]{64}$/.test(row.sourceRevision) ||
        !/^[a-f0-9]{64}$/.test(row.semanticHash),
    )
  ) {
    throw new Error('teaching-registry-selection-invalid');
  }

  const imports: string[] = [];
  const localeEntries: string[] = [];
  const bindingEntries = rows.map(
    (row) =>
      `  Object.freeze({ ordinal: ${row.ordinal}, batch: ${row.batch}, formulaId: '${row.formulaId}', sourceRevision: '${row.sourceRevision}', semanticHash: '${row.semanticHash}' }),`,
  );
  const selectionSha256 = createHash('sha256').update(selectionBytes).digest('hex');
  const authorityExports = (
    [
      ['ANCHORS', 'anchors'],
      ['RUNTIME_INDEX', 'runtimeIndex'],
      ['LEDGER', 'ledger'],
      ['APPROVAL', 'approval'],
      ['APPROVAL_PACKET', 'approvalPacket'],
    ] as const
  ).flatMap(([constant, key]) => {
    const bytes = authorityBytes[key];
    const sha256 = createHash('sha256').update(bytes).digest('hex');
    return [
      `export const TEACHING_${constant}_SHA256_V1 = '${sha256}' as const;`,
      `export const TEACHING_${constant}_RAW_V1 = ${JSON.stringify(bytes.toString('utf8'))} as const;`,
    ];
  });
  for (const locale of LOCALES) {
    const directory = join(
      repositoryRoot,
      'resources/formula-library/v1/teaching-content',
      locale,
    );
    const actualFiles = readdirSync(directory).filter((name) => name.endsWith('.json')).sort();
    const expectedFiles = rows.map((row) => `${row.formulaId}.json`).sort();
    if (JSON.stringify(actualFiles) !== JSON.stringify(expectedFiles)) {
      throw new Error(`teaching-registry-${locale}-set-invalid`);
    }
    const entries: string[] = [];
    rows.forEach((row, index) => {
      const identifier = `${locale}_${String(index + 1).padStart(2, '0')}`;
      imports.push(
        `import ${identifier} from '../../../resources/formula-library/v1/teaching-content/${locale}/${row.formulaId}.json';`,
      );
      entries.push(`    '${row.formulaId}': ${identifier},`);
    });
    localeEntries.push(
      `  ${locale}: Object.freeze({\n${entries.join('\n')}\n  }),`,
    );
  }

  return `${[
    '// This file is generated by scripts/generate-teaching-content-registry.ts.',
    '// Do not edit by hand; run npm run formula:teaching-registry:write.',
    ...imports,
    '',
    "export const TEACHING_CONTENT_LOCALES_V1 = ['en', 'zh', 'pt', 'ko', 'ru', 'es', 'fr'] as const;",
    `export const TEACHING_SELECTION_SHA256_V1 = '${selectionSha256}' as const;`,
    `export const TEACHING_SELECTION_RAW_V1 = ${JSON.stringify(selectionBytes.toString('utf8'))} as const;`,
    ...authorityExports,
    '',
    'export type TeachingContentLocaleV1 = (typeof TEACHING_CONTENT_LOCALES_V1)[number];',
    'export interface GeneratedTeachingSelectionBindingV1 {',
    '  readonly ordinal: number;',
    '  readonly batch: number;',
    '  readonly formulaId: string;',
    '  readonly sourceRevision: string;',
    '  readonly semanticHash: string;',
    '}',
    'export const TEACHING_SELECTION_BINDINGS_V1: readonly GeneratedTeachingSelectionBindingV1[] = Object.freeze([',
    ...bindingEntries,
    ']);',
    '',
    'export type TeachingContentRegistryV1 = Readonly<Record<',
    '  TeachingContentLocaleV1,',
    '  Readonly<Record<string, unknown>>',
    '>>;',
    '',
    'export const TEACHING_CONTENT_REGISTRY_V1: TeachingContentRegistryV1 = Object.freeze({',
    ...localeEntries,
    '});',
  ].join('\n')}\n`;
}

export function generateTeachingContentRegistryV1(
  repositoryRoot: string,
  write: boolean,
): { readonly output: string; readonly outputPath: string } {
  const output = buildRegistrySource(repositoryRoot);
  const outputPath = join(repositoryRoot, OUTPUT_PATH);
  if (write) writeFileSync(outputPath, output, 'utf8');
  else if (readFileSync(outputPath, 'utf8') !== output) {
    throw new Error('teaching-content-registry-stale');
  }
  return { output, outputPath };
}

async function main(): Promise<void> {
  const repositoryRoot = process.cwd();
  const write = process.argv.includes('--write');
  const result = generateTeachingContentRegistryV1(repositoryRoot, write);
  process.stdout.write(
    `${JSON.stringify({ ok: true, write, bytes: Buffer.byteLength(result.output) })}\n`,
  );
}

if (
  process.argv[1] &&
  pathToFileURL(resolve(process.argv[1])).href === import.meta.url
) {
  main().catch((error: unknown) => {
    process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`);
    process.exitCode = 1;
  });
}
