import { readFileSync } from "node:fs";
import { join } from "node:path";
import baseline from "../resources/formula-library/v1/julia-final-capability-census.v1.json";
import predecessor from "../resources/formula-library/v1/julia-pixel-final-capability-census.v2.json";
import predecessorAudit from "../resources/formula-library/v1/julia-pixel-final-recovery-audit.v1.json";
import contract from "../resources/formula-library/v1/julia-pixel-recovery-contract.v1.json";
import corrective from "../resources/formula-library/v1/julia-classic-regression-corrective.v1.json";
import renderer from "../resources/formula-library/v1/julia-classic-regression-renderer-evidence.v1.json";
import { canonicalJsonV1, sha256HexSyncV1 } from "../src/engine/formulas/v1/revisions";
import { JULIA_FINAL_RECOVERY_V3_SOURCE_BINDING_PATHS, juliaFinalRecoveryV3ContentHash, parseJuliaFinalRecoveryAuditV2, parseJuliaPixelActivationHandoffV2, parseJuliaPixelFinalAuthorityManifestV2, parseJuliaPixelFinalCapabilityCensusV3, verifyJuliaFinalRecoveryActivationHandoffV2 } from "../src/engine/formulas/v1/julia-final-recovery-v3";

type Json = Record<string, unknown>;
const ROOT = process.cwd(); const RESOURCE = join(ROOT, "resources/formula-library/v1");
const get = (name: string): Json => JSON.parse(readFileSync(join(RESOURCE, name), "utf8")) as Json;
const canon = (value: unknown, budget = 1_048_576) => canonicalJsonV1(value, budget);
const same = (left: unknown, right: unknown) => canon(left) === canon(right);
const ref = (digest: string) => `sha256:${digest}`;

function main(): void {
  const census = get("julia-pixel-final-capability-census.v3.json"); const authority = get("julia-pixel-final-authority-manifest.v2.json"); const handoff = get("julia-pixel-activation-handoff.v2.json"); const audit = get("julia-pixel-final-recovery-audit.v2.json");
  if (!parseJuliaPixelFinalCapabilityCensusV3(census).ok || !parseJuliaPixelFinalAuthorityManifestV2(authority).ok || !parseJuliaPixelActivationHandoffV2(handoff).ok || !parseJuliaFinalRecoveryAuditV2(audit).ok) throw new Error("output-parser-rejection");
  const sourceContents = Object.fromEntries(JULIA_FINAL_RECOVERY_V3_SOURCE_BINDING_PATHS.map((path) => [path, readFileSync(join(ROOT, path), "utf8")])); const sourceBindings = Object.fromEntries(Object.entries(sourceContents).map(([path, contents]) => [path, sha256HexSyncV1(contents)]));
  const oldRows = predecessor.rows as Json[]; const finalRows = census.rows as Json[]; const correctiveRows = corrective.rows as Json[]; const rendererRows = renderer.rows as Json[]; const correction = new Map(correctiveRows.map((row) => [String(row.formulaId), row])); const rendered = new Map(rendererRows.filter((row) => row.status === "passed").map((row) => [String(row.formulaId), row]));
  const eligible = oldRows.filter((row) => row.modeClass === "classic-julia" && row.finalStatus === "held" && row.supportLane === "none" && row.remediationLane === "canonical-rebind").map((row) => String(row.formulaId)).sort(); const regression = [...(predecessorAudit.regressionIds as string[])]; const targets = eligible.filter((id) => correction.has(id) && rendered.has(id) && regression.includes(id));
  if (!same(targets, correctiveRows.map((row) => row.formulaId).sort()) || !same(targets, rendererRows.filter((row) => row.status === "passed").map((row) => row.formulaId).sort()) || targets.some((id) => !regression.includes(id)) || targets.length !== 7 || finalRows.length !== 534 || !same(finalRows.map((row) => row.formulaId), oldRows.map((row) => row.formulaId))) throw new Error("target-or-order-invalid");
  const targetSet = new Set(targets); const roleOrder = ["role:pixel-seed", "role:pixel-constant", "role:julia-constant", "role:derived-pixel-constant", "role:formula-parameter", "role:dynamic-orbit-state", "role:bailout-control", "role:unresolved"];
  for (let index = 0; index < finalRows.length; index += 1) { const old = oldRows[index]!; const row = finalRows[index]!; if (!targetSet.has(String(old.formulaId))) { if (!same(old, row)) throw new Error("non-target-mutated"); continue; } const c = correction.get(String(old.formulaId))!; const e = rendered.get(String(old.formulaId))!; const role = c.supportLane === "source-split-direct" ? "role:pixel-constant" : "role:derived-pixel-constant"; const expected = { ...old, roles: [...new Set([...(old.roles as string[]).filter((item) => item !== "role:pixel-constant" && item !== "role:derived-pixel-constant"), role])].sort((a, b) => roleOrder.indexOf(a) - roleOrder.indexOf(b)), supportLane: c.supportLane, remediationLane: "none", rewriteClass: "E0-operational-equivalence", finalStatus: "supported", identityChangeProposalRef: null, evidence: { tier0: "pass", tier1: "pass", tier2: "pass", identityReview: "not-required", e1Supplement: "not-required", e1SealedHoldout: "not-required", notApplicableReview: "not-required" }, receipts: { ...(old.receipts as Json), sourceAuthority: ref(String(c.candidateSourceRevision)), directPixelSeed: ref(String((c.e0 as Json).analysisContentHash)), tier0: ref(String(c.rowReceipt)), tier1: ref(String(c.rowReceipt)), tier2: ref(String(e.receipt)), identityReview: null, e1Supplement: null, e1SealedHoldout: null, notApplicableReview: null }, authority: { authorityState: "sealed", supersededBy: null, withdrawnBy: null } }; if (!same(row, expected)) throw new Error("target-reconstruction-invalid"); }
  const status = (name: string) => finalRows.filter((row) => row.finalStatus === name).map((row) => String(row.formulaId)).sort(); const supported = status("supported"); const held = status("held"); const blocked = status("blocked"); const unknown = status("unknown"); const baselineSupported = (baseline.rows as Json[]).filter((row) => row.status === "supported").map((row) => String(row.formulaId)).sort(); const gains = supported.filter((id) => !baselineSupported.includes(id)); const regressions = baselineSupported.filter((id) => !supported.includes(id));
  const expectedInputs = [String(baseline.contentHash), String(predecessor.contentHash), String(contract.contentHash), String(corrective.contentHash), String(renderer.contentHash)].sort();
  if ([supported.length, held.length, blocked.length, unknown.length, gains.length, regressions.length, targets.length].join(",") !== "186,160,72,116,36,20,7" || census.contentHash !== juliaFinalRecoveryV3ContentHash(census) || authority.contentHash !== juliaFinalRecoveryV3ContentHash(authority) || handoff.contentHash !== juliaFinalRecoveryV3ContentHash(handoff) || audit.contentHash !== juliaFinalRecoveryV3ContentHash(audit) || !same(authority.sourceBindings, sourceBindings) || !same(audit.sourceBindings, sourceBindings) || !same(authority.inputAuthorityContentHashes, expectedInputs) || handoff.supportedClassicRowSetDigest !== sha256HexSyncV1(canon(supported, 4096)) || handoff.regressionSetDigest !== sha256HexSyncV1(canon(regressions, 4096)) || !same(audit.supportedClassicIds, supported) || !same(audit.gainIds, gains) || !same(audit.regressionIds, regressions) || !same(audit.recoveredRegressionIds, targets)) throw new Error("closure-cross-check-invalid");
  const result = verifyJuliaFinalRecoveryActivationHandoffV2(handoff, census, authority, audit, baseline, predecessor, contract, predecessorAudit, corrective, renderer, sourceContents); if (result.code !== "julia-final-recovery-v3-review-pending") throw new Error("consumer-rejection");
  process.stdout.write(`${JSON.stringify({ ok: true, rows: 534, supported: 186, held: 160, blocked: 72, unknown: 116, gains: 36, regressions: 20, recovered: 7 })}\n`);
}
main();
